-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 14:39:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Vinicula
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vinicula
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vinicula` DEFAULT CHARACTER SET utf8 ;
USE `Vinicula` ;

-- -----------------------------------------------------
-- Table `Vinicula`.`Propriedade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Propriedade` (
  `Nome` VARCHAR(50) NOT NULL,
  `Administrador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Contato` (
  `Propriedade_Nome` VARCHAR(50) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Propriedade_Nome`),
  UNIQUE INDEX `Propriedade_Nome_UNIQUE` (`Propriedade_Nome` ASC),
  UNIQUE INDEX `Endereço_UNIQUE` (`Endereço` ASC),
  CONSTRAINT `fk_Contato_Propriedade1`
    FOREIGN KEY (`Propriedade_Nome`)
    REFERENCES `Vinicula`.`Propriedade` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Terroir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Terroir` (
  `Propriedade_Nome` VARCHAR(50) NOT NULL,
  `Tipo de Solo` VARCHAR(50) NOT NULL,
  `Altitude (m)` FLOAT NOT NULL,
  `Umidade` FLOAT NOT NULL,
  `Índice Pluviométrico (%)` FLOAT NOT NULL,
  `Clima (°C)` FLOAT NOT NULL,
  `Região` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Região_UNIQUE` (`Região` ASC),
  PRIMARY KEY (`Propriedade_Nome`),
  CONSTRAINT `fk_Terroar_Propriedade1`
    FOREIGN KEY (`Propriedade_Nome`)
    REFERENCES `Vinicula`.`Propriedade` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Parreiral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Parreiral` (
  `idParreiral` INT NOT NULL AUTO_INCREMENT,
  `Propriedade_Nome` VARCHAR(50) NOT NULL,
  `Vinhas` INT NOT NULL,
  `Área (m²)` FLOAT NOT NULL,
  `Plantio` DATETIME NOT NULL,
  PRIMARY KEY (`idParreiral`, `Propriedade_Nome`),
  INDEX `fk_Parreiral_Propriedade1_idx` (`Propriedade_Nome` ASC),
  CONSTRAINT `fk_Parreiral_Propriedade1`
    FOREIGN KEY (`Propriedade_Nome`)
    REFERENCES `Vinicula`.`Propriedade` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Cepa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Cepa` (
  `Nome` VARCHAR(45) NOT NULL,
  `Parreiral_idParreiral` INT NOT NULL,
  `Região de Origem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`, `Parreiral_idParreiral`),
  INDEX `fk_Cepa_Parreiral1_idx` (`Parreiral_idParreiral` ASC),
  CONSTRAINT `fk_Cepa_Parreiral1`
    FOREIGN KEY (`Parreiral_idParreiral`)
    REFERENCES `Vinicula`.`Parreiral` (`idParreiral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Colheita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Colheita` (
  `idColheita` INT NOT NULL AUTO_INCREMENT,
  `Parreiral_idParreiral` INT NOT NULL,
  `diaColheita` INT NOT NULL,
  `mesColheita` INT NOT NULL,
  `anoColheita` INT NOT NULL,
  `Material` VARCHAR(45) NOT NULL,
  `Maturação` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idColheita`, `Parreiral_idParreiral`),
  INDEX `fk_Colheita_Parreiral1_idx` (`Parreiral_idParreiral` ASC),
  UNIQUE INDEX `idColheita_UNIQUE` (`idColheita` ASC),
  UNIQUE INDEX `anoColheita_UNIQUE` (`anoColheita` ASC),
  CONSTRAINT `fk_Colheita_Parreiral1`
    FOREIGN KEY (`Parreiral_idParreiral`)
    REFERENCES `Vinicula`.`Parreiral` (`idParreiral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Vinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Vinho` (
  `codVinho` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Rótulo` VARCHAR(50) NOT NULL,
  `Classificação` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codVinho`, `Nome`),
  UNIQUE INDEX `codVinho_UNIQUE` (`codVinho` ASC),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  UNIQUE INDEX `Rótulo_UNIQUE` (`Rótulo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Safra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Safra` (
  `Colheita_idColheita` INT NOT NULL,
  `Ano` INT NOT NULL,
  `Garrafas` INT(45) NOT NULL,
  `Vinho_codVinho` INT NOT NULL,
  `Vinho_Nome` VARCHAR(45) NOT NULL,
  `Avaliação` INT NULL,
  PRIMARY KEY (`Colheita_idColheita`),
  INDEX `fk_Safra_Colheita1_idx` (`Colheita_idColheita` ASC),
  UNIQUE INDEX `Colheita_idColheita_UNIQUE` (`Colheita_idColheita` ASC),
  INDEX `fk_Safra_Vinho1_idx` (`Vinho_codVinho` ASC, `Vinho_Nome` ASC),
  CONSTRAINT `fk_Safra_Colheita1`
    FOREIGN KEY (`Colheita_idColheita`)
    REFERENCES `Vinicula`.`Colheita` (`idColheita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Safra_Vinho1`
    FOREIGN KEY (`Vinho_codVinho` , `Vinho_Nome`)
    REFERENCES `Vinicula`.`Vinho` (`codVinho` , `Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Telefones` (
  `idTelefones` INT NOT NULL AUTO_INCREMENT,
  `Contato_Propriedade_Nome` VARCHAR(50) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTelefones`),
  UNIQUE INDEX `idTelefone_UNIQUE` (`idTelefones` ASC),
  UNIQUE INDEX `Telefone_UNIQUE` (`Telefone` ASC),
  INDEX `fk_Telefones_Contato1_idx` (`Contato_Propriedade_Nome` ASC),
  CONSTRAINT `fk_Telefones_Contato1`
    FOREIGN KEY (`Contato_Propriedade_Nome`)
    REFERENCES `Vinicula`.`Contato` (`Propriedade_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vinicula`.`Emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vinicula`.`Emails` (
  `idEmail` INT NOT NULL AUTO_INCREMENT,
  `Contato_Propriedade_Nome` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmail`),
  UNIQUE INDEX `idEmail_UNIQUE` (`idEmail` ASC),
  INDEX `fk_Emails_Contato1_idx` (`Contato_Propriedade_Nome` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  CONSTRAINT `fk_Emails_Contato1`
    FOREIGN KEY (`Contato_Propriedade_Nome`)
    REFERENCES `Vinicula`.`Contato` (`Propriedade_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
